import PDFDocument from "pdfkit";

export const generatePDFBuffer = (text) => {
  return new Promise((resolve) => {
    // Increased margin for professional look
    const doc = new PDFDocument({ margin: 60, size: 'A4' });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    // --- TITLE ---
    doc
      .font("Helvetica-Bold")
      .fontSize(22)
      .fillColor("#2563eb") // Professional Blue Color for Title
      .text("AI Resume Enhancement", { align: "center" });

    doc
      .fontSize(10)
      .fillColor("#64748b") // Grey subtitle
      .text("Generated by Curson AI Recruiter", { align: "center" });

    doc.moveDown(2); // Big gap after title

    // --- CONTENT PARSING ---
    const lines = text.split("\n");

    lines.forEach((line) => {
      const trimmed = line.trim();

      // 1. CHECK FOR HEADERS (e.g., "1. SECTION TITLE")
      if (/^\d+\./.test(trimmed)) {
        doc.moveDown(1.5); // Large gap before new section
        doc
          .font("Helvetica-Bold")
          .fontSize(14)
          .fillColor("#0f172a") // Dark Slate (Almost Black)
          .text(trimmed.toUpperCase()); // Force Uppercase for headers
        doc.moveDown(0.5); // Small gap after header
      } 
      
      // 2. CHECK FOR BULLET POINTS (e.g., "- Something")
      else if (trimmed.startsWith("-") || trimmed.startsWith("•")) {
        doc
          .font("Helvetica")
          .fontSize(11)
          .fillColor("#334155") // Standard text color
          .text(trimmed, {
            indent: 20,    // Indent bullets
            align: "left",
            lineGap: 4     // Breathing room between lines
          });
      } 
      
      // 3. EMPTY LINES (For spacing)
      else if (trimmed === "") {
        doc.moveDown(0.5); 
      } 
      
      // 4. REGULAR PARAGRAPHS
      else {
        doc
          .font("Helvetica")
          .fontSize(11)
          .fillColor("#334155")
          .text(trimmed, {
            align: "left",
            lineGap: 5 // Readable line height
          });
      }
    });

    doc.end();
  });
};